// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZSvNPwSd0xRdF2nzeWb_56j3eW3pVTmo',
    appId: '1:794536168653:web:e50cecb36dc6ca8527ad84',
    messagingSenderId: '794536168653',
    projectId: 'saferoom-c9b4d',
    authDomain: 'saferoom-c9b4d.firebaseapp.com',
    storageBucket: 'saferoom-c9b4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwDm5ObUPoOPyd3YAKQRYVrfG1CL9bZI0',
    appId: '1:794536168653:android:184e05e44091540a27ad84',
    messagingSenderId: '794536168653',
    projectId: 'saferoom-c9b4d',
    storageBucket: 'saferoom-c9b4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNDRKxi-7uh9jSGTO9Gr6YEgPm0Cpo6QU',
    appId: '1:794536168653:ios:213d2d2ebc4488a927ad84',
    messagingSenderId: '794536168653',
    projectId: 'saferoom-c9b4d',
    storageBucket: 'saferoom-c9b4d.appspot.com',
    iosClientId: '794536168653-7osl5o25ahhshbeftpd1s3g2kbb2s7fm.apps.googleusercontent.com',
    iosBundleId: 'com.saferoom.saferoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNDRKxi-7uh9jSGTO9Gr6YEgPm0Cpo6QU',
    appId: '1:794536168653:ios:213d2d2ebc4488a927ad84',
    messagingSenderId: '794536168653',
    projectId: 'saferoom-c9b4d',
    storageBucket: 'saferoom-c9b4d.appspot.com',
    iosClientId: '794536168653-7osl5o25ahhshbeftpd1s3g2kbb2s7fm.apps.googleusercontent.com',
    iosBundleId: 'com.saferoom.saferoom',
  );
}
